apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sports2020
  namespace: argocd
  project: default
  source:
    repoURL: https://github.com/bfv/sports2020-argocd-config.git
    targetRevision: HEAD
    path: dev
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: application.hostname
          value: sports2020-argocd.bfv.io
        - name: application.environment
          value: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: sports2020-argocd

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
