apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  labels:
    ns: sports2020-argocd
    type: backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: backup-1
  # selector:
  #   matchLabels:
  #     ns: sports2020-argocd
  #     type: backup
