apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.application.name }}-ingressroute

spec:
  entryPoints:                     
    - web
  routes:                          
  - kind: Rule
    match: Host(`{{ .Values.application.hostname }}`) && PathPrefix(`/data`)   
    services:                       
      - name: {{ .Values.pas.service }}
        port: 80
    middlewares:
      - name: strip-prefix
      - name: add-web-prefix

  - kind: Rule
    match: Host(`{{ .Values.application.hostname }}`) && PathPrefix(`/`)   
    services:                       
      - name: {{ .Values.webui.service }}
        port: 80
