apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.application.name }}-ingressroute

spec:
  entryPoints:                     
    - websecure
  routes:                          
  - kind: Rule
    match: PathPrefix(`/data`)
    services:                       
      - name: {{ .Values.pas.service }}
        port: 80
    middlewares:
      - name: strip-prefix
      - name: add-web-prefix

  - kind: Rule
    match: PathPrefix(`/`)
    services:                       
      - name: {{ .Values.webui.service }}
        port: 80
