apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pas.service }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.application.name }}
    component: pas
  ports:
  - name: http
    port: 80
    targetPort: 8810
    