apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webui.service }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.application.name }}
    component: web-ui
  ports:
  - name: http
    port: 80
    targetPort: 80

