apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.application.name }}
      component: webui
  template:
    metadata:
      labels:
        app: {{ .Values.application.name }}
        component: webui
    spec:
      containers:
      - name: "{{ .Values.application.name }}-webui"
        image: {{ .Values.webui.container.image }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Mi"
            cpu: "10m"
          limits:
            memory: "10Mi"
            cpu: "100m"
        ports:
          - containerPort: {{ .Values.webui.container.port }}
        
